name: Build
on: [ push ]
jobs:
  Java:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        distribution:
          - temurin
          - zulu
          - adopt
          - liberica
          - microsoft
          - corretto
          - semeru
          - oracle
          - dragonwell
        version:
          - 21
          - 22
          - 23
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
          cache: gradle

      - name: Test
        run: ./gradlew test --stacktrace
